### ISSUE TITLE
非常感谢作者的工作

### ISSUE THREAD

**Issue by Hyumtaro** [Jin-bao/NCU-thesis#2]
倾心于LaTeX使用的便捷，一直希望能够以此编写自己的学位论文和课程论文，但苦于没有合适的模板，而自己也没有足够的能力开发出一套好用的模板，所以不得不在word上反复地调整格式。作者的这项工作使得我等在写作时只需要专注于内容即可，确实是一大善举。希望学校可以将此项工作作为毕业论文的TeX模板。最后再次感谢作者的工作，祝好。

**Comment by Jin-bao** [comment]
感谢您的肯定，很高兴自己的工作能帮到大家！模板的完善需要大家的反馈和推广，当足够稳定的时候，我会联系学校相关部门。
