### ISSUE TITLE
编译之后，界面上输入文本后全是方框

### ISSUE THREAD

**Issue by Bobchest** [Jin-bao/NCU-thesis#3]

**Comment by Jin-bao** [comment]
![image](https://user-images.githubusercontent.com/46128188/222707678-28c7e641-5226-423f-990d-83dea118a6d8.png)

模板默认的稿件状态是 `draft` 模式，该模式会显示布局线条。可以在调用 `ncuthesis` 时指定 `final` 选项：
```
\documentclass[final]{ncuthesis}
%% 或者
\documentclass[doc=final]{ncuthesis}
```
 这样就不会有布局线条了。

关于稿件状态，请查阅 NCU-thesis-guide.pdf 第 9 页的内容。

**Comment by Jin-bao** [comment]
其他用户也不适应默认 `draft` 模式，看来下次得将默认值改为 `final`。

**Comment by Bobchest** [comment]
改为final后，重新编译文本仍显示为方框
何解



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月3日(周五) 晚上7:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jin-bao/NCU-thesis] 编译之后，界面上输入文本后全是方框 (Issue #3)




 

 
模板默认的稿件状态是 draft 模式，该模式会显示布局线条。可以在调用 ncuthesis 时指定 final 选项：
 '''
 \documentclass[final]{ncuthesis}
 %% 或者
 \documentclass[doc=final]{ncuthesis}
 '''
 这样就不会有布局线条了。
 
关于稿件状态，请查阅 NCU-thesis-guide.pdf 第 9 页的内容。

**Comment by Bobchest** [comment]
并不是布局线条的问题，是我输入的文本全都被一个个方框代替了，输出为pdf也显示没有文本，，只有一堆方框

**Comment by Jin-bao** [comment]
![image](https://user-images.githubusercontent.com/46128188/222724245-10e032fd-9333-4d4a-95e1-e0f70ac02eb1.png)

我复现了你所描述的，这种情况是因为你那边缺少字体。模板最新版本为了避免版权问题，就不再打包字体了。模板默认需要宋体、黑体、仿宋、楷体四种字体，你那边是 Mac 系统还是 Linux 系统，这两种操作系统默认并没有上述四种字体。如果是 Windows，也请检查是否安装这四种字体。

**Comment by Bobchest** [comment]
我的系统Windows11，请问windows怎么检查并安装这四种字体呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月3日(周五) 晚上8:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jin-bao/NCU-thesis] 编译之后，界面上输入文本后全是方框 (Issue #3)




 

 
我复现了你所描述的，这种情况是因为你那边缺少字体。模板最新版本为了避免版权问题，就不再打包字体了。模板默认需要宋体、黑体、仿宋、楷体四种字体，你那边是 Mac 系统还是 Linux 系统，这两种操作系统默认并没有上述四种字体。如果是 Windows，也请检查是否安装这四种字体。

**Comment by Bobchest** [comment]
确实显示缺少字体



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月3日(周五) 晚上8:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jin-bao/NCU-thesis] 编译之后，界面上输入文本后全是方框 (Issue #3)




 

 
我复现了你所描述的，这种情况是因为你那边缺少字体。模板最新版本为了避免版权问题，就不再打包字体了。模板默认需要宋体、黑体、仿宋、楷体四种字体，你那边是 Mac 系统还是 Linux 系统，这两种操作系统默认并没有上述四种字体。如果是 Windows，也请检查是否安装这四种字体。

**Comment by Jin-bao** [comment]
进入 `C:\Windows\Fonts` 文件夹，看看是否有下面的四种字体

![image](https://user-images.githubusercontent.com/46128188/222725687-fdeeb804-3da9-40b3-a335-8b3f7685b5d9.png)

如果有，则可能是编译方式不对。如果没有，从别人电脑里复制，然后在你电脑上 `为所有人安装`。注意一定要 `为所有人安装`，如果仅是 `安装`，可能依然访问不到。

**Comment by Jin-bao** [comment]
我实在好奇为什么 Windows 会没有这四种字体，这四种字体都是中文版 Windows 默认附带的，难道你的是英文版的？

**Comment by Bobchest** [comment]
我在我的电脑上找到了这四种字体，那么现在是考虑编译的问题吗？日志里好像有几个关于字体的保存



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月3日(周五) 晚上9:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jin-bao/NCU-thesis] 编译之后，界面上输入文本后全是方框 (Issue #3)




 
我实在好奇为什么 Windows 会没有这四种字体，这四种字体都是中文版 Windows 默认附带的，难道你的是英文版的？

**Comment by Jin-bao** [comment]
你可以截图让我看看具体报错或警告信息。我这边可没有水晶球，不能猜到你那边的具体情况。

**Comment by Bobchest** [comment]
这是部分报错，需要看代码吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月3日(周五) 晚上9:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jin-bao/NCU-thesis] 编译之后，界面上输入文本后全是方框 (Issue #3)




 
你可以截图让我看看具体报错或警告信息。我这边可没有水晶球，不能猜到你那边的具体情况。

**Comment by Jin-bao** [comment]
要看到具体报错信息才能知道怎么解决。截图或者将日志信息发出来。

**Comment by Bobchest** [comment]
我把报错日志复制下来了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jin-bao/NCU-thesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月3日(星期五) 晚上9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jin-bao/NCU-thesis] 编译之后，界面上输入文本后全是方框 (Issue #3)





 
要看到具体报错信息才能知道怎么解决。

**Comment by Jin-bao** [comment]
那就发出来，我要看到报错或日志信息，才能知道如何解决。

**Comment by Jin-bao** [comment]
抱歉，这次发布遗留了一些之前版本的代码，但很巧的是在测试过程中没被发现，这便导致了你那边的问题。我现在取消这次的发布。

**Comment by Bobchest** [comment]
那有可以稳定使用的版本吗？谢谢😊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月3日(周五) 晚上10:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jin-bao/NCU-thesis] 编译之后，界面上输入文本后全是方框 (Issue #3)




 
抱歉，这次发布遗留了一些之前版本的代码，但很巧的是在测试过程中没被发现，这便导致了你那边的问题。我现在取消这次的发布。

**Comment by Jin-bao** [comment]
我已经删除这次的发布了，明天再发布出来就是没问题的了。

**Comment by Jin-bao** [comment]
修改好的版本已经发布了，这次应该不会出问题。感谢你提出的 issue，纠正了一个比较致命的失误。

**Comment by Bobchest** [comment]
好的，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月3日(周五) 晚上11:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jin-bao/NCU-thesis] 编译之后，界面上输入文本后全是方框 (Issue #3)




 
我已经删除这次的发布了，明天再发布出来就是没问题的了。

**Comment by Bobchest** [comment]
不好意思，打扰你了！我今天在github下载了最新的zip后，在overleaf中编译仍然出现了昨天的那种情况。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jin-bao/NCU-thesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月3日(星期五) 晚上11:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jin-bao/NCU-thesis] 编译之后，界面上输入文本后全是方框 (Issue #3)





 
修改好的版本已经发布了，这次应该不会出问题。感谢你提出的 issue，解决了一个比较致命的问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

使用过程.webm (10.24M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=76346666a81665c690c434e342340b164c40075753570f5b1906565e51195b5803054b0750525b14060c0000550d5a5d00550050643939f38de7a5df9987f5174351040b6409&t=exs_ftn_download&code=44ffd499




页面全是方框.webm (2.96M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=733664333ef6e19e91c636b64565034e4d42000602565704180f5d015a485700575349015756054c00520505530303550d060500637431b386f582fbc8aff6d68889961d1400530c350b&t=exs_ftn_download&code=56d3ce1a




报错.webm (9.01M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=0c656633a8b909ce969534b61063541e4a115f55050551001f57560b054e030507534b560254021c545c50570706020250065f51366a66809ad18b1d4106045c3258&t=exs_ftn_download&code=2ef36cf1




原始日志.txt (193.0K, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=7966616395cececd9c9633e64035001d401255055e010501155755505718030b00044c025207541f5d05055a070704545e07505b663932e695acddabb3e38c1c4c1e15635b&t=exs_ftn_download&code=8facf522

**Comment by Jin-bao** [comment]
问题是一样的，overleaf 的后端没有宋、黑、仿、楷四种字体。之后的版本我再考虑支持。

**Comment by note286** [comment]
> 问题是一样的，overleaf 的后端没有宋、黑、仿、楷四种字体。之后的版本我再考虑支持。

可以参考参考思路，[note286/xduts: 西安电子科技大学LaTeX套装](https://github.com/note286/xduts)。

**Comment by Jin-bao** [comment]
> 可以参考参考思路，[note286/xduts: 西安电子科技大学LaTeX套装](https://github.com/note286/xduts)。

对的，其实好解决，默认 fandol 就好。不过我没用过 overleaf，不知道 overleaf 该怎样修改字体。

**Comment by note286** [comment]
> 对的，其实好解决，默认 fandol 就好。不过我没用过 overleaf，不知道 overleaf 该怎样修改字体。

它可以调用内置的字体，也可以调用文件夹里，也就是相对目录里的字体文件，使用文件名调用即可，就不用安装了，和本地不安装字体直接调用文件名是一致的。

**Comment by Jin-bao** [comment]
> 它可以调用内置的字体，也可以调用文件夹里，也就是相对目录里的字体文件，使用文件名调用即可，就不用安装了，和本地不安装字体直接调用文件名是一致的。

这就又回到最初的问题上了。为了避免版权问题，便不再给模板打包字体了，只使用操作系统或发行版的字体。如果设置相对路径，我不确定用户是否能把正确的字体放在正确的路径。

**Comment by Bobchest** [comment]
那哪行代码是指定语言文件夹的呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月4日(周六) 晚上6:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jin-bao/NCU-thesis] 编译之后，界面上输入文本后全是方框 (Issue #3)




  
它可以调用内置的字体，也可以调用文件夹里，也就是相对目录里的字体文件，使用文件名调用即可，就不用安装了，和本地不安装字体直接调用文件名是一致的。
  
这就又回到最初的问题上了。为了避免版权问题，便不再给模板打包字体了，只使用操作系统或发行版的字体。如果设置相对路径，我不确定用户是否能把正确的字体放在正确的路径。

**Comment by note286** [comment]
> 这就又回到最初的问题上了。为了避免版权问题，便不再给模板打包字体了，只使用操作系统或发行版的字体。如果设置相对路径，我不确定用户是否能把正确的字体放在正确的路径。

默认中英文均使用TeX Live内置字体，直接编译即可。如果用户想要更换字体，就必须看手册了，根据手册提供的接口切换，xduts里还给出了一个字体存放目录，直接放在那里即可，用户是可以自定义字体目录的。那你要是说用户就是不看手册的话，这种用户就别管了。

我自认为目前xduts的接口设计还是可以的。字体方面，用户的选择比较自由，也比较易用。

**Comment by Jin-bao** [comment]
> 那哪行代码是指定语言文件夹的呢

这和上百行代码有关。。。

**Comment by Jin-bao** [comment]
> 默认中英文均使用TeX Live内置字体，直接编译即可。如果用户想要更换字体，就必须看手册了，根据手册提供的接口切换，xduts里还给出了一个字体存放目录，直接放在那里即可，用户是可以自定义字体目录的。那你要是说用户就是不看手册的话，这种用户就别管了。
> 
> 我自认为目前xduts的接口设计还是可以的。字体方面，用户的选择比较自由，也比较易用。

我也可以采用这样的方式。感谢你的思路~
